name: Build and Publish Docker Image to Docker Hub

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "docker tag"
        required: true
        default: "0.0.0"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Hub Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --tag ${{ secrets.DOCKERHUB_USERNAME }}/yals:${{ inputs.tag }}

      - name: Docker Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/yals:${{ inputs.tag }}
